### ISSUE TITLE
Layout: errors while using CSP and MOVE_SCRIPTS_TO_BOTTOM at the same time

### ISSUE THREAD

**Issue by lih13800** [primefaces-extensions/primefaces-extensions#1509] opened 2024-04-03 22:01 UTC
### Describe the bug

Thank you for fixing issues about CSP update on Primefer 13.0.2: https://github.com/primefaces/primefaces/issues/10658

After I updated the new version, I found that there are some errors if I using the CSP and MOVE_SCRIPTS_TO_BOTTOM at the same time.

In the test sample, we can see following errors on the console:

![137-notdefined](https://github.com/primefaces-extensions/primefaces-extensions/assets/114792410/ba498a74-490a-4ead-aae0-9fbd89d32301)

These errors is related to the input text component and command button component. The errors occur only when the component is inside < pe:layout>  component.

If we remove either CSP or MOVE_SCRIPTS_TO_BOTTOM from web.xml, the error would occur. 

Reproduced sample:
[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/14858854/primefaces-test.zip)

### Reproducer

1. Open the page: http://localhost:8080/primefaces-test/
2. Open the browser, then we can see the errors on console

### Expected behavior

No errors on the console

### PrimeFaces Extensions version

13.0.7

### JSF implementation

Mojarra

### JSF version

2.2

### Browser(s)

Firefox 124.0.1

**Comment by melloware** [comment] 2024-04-03 22:53
I will take a look thanks!  I use layout in production with CSP so I will check out what is going on.

**Comment by melloware** [comment] 2024-04-04 11:13
OK well the issue is your InputText is the only script on the page not being moved to the bottom.

```xml
<script id="frmTest:j_idt8_s" type="text/javascript" nonce="YzM5MTQxMDEtOGZiNC00NDhlLWEwZTMtYWEwMGEyZGM5YTVi">PrimeFaces.cw("InputText","widget_frmTest_j_idt8",{id:"frmTest:j_idt8"});</script>
```

So that inline script runs for PrimeFaces createwidget even though PrimeFaces has not been initialized yet because all the scripts are at the bottom.

I think this is because the center panel gets delayed in rendering.  The showcase has the same setup but it does not seem to happen with the Showcase when I turn CSP on.  The only difference is I am using the GSON options for layout.

```xml
<pe:layout id="fpl" widgetVar="fullLayoutWidget" options="#{showcaseLayout.options}">
```

SO I wonder if using the GSON options is somehow different.

**Comment by melloware** [comment] 2024-04-04 15:36
Yeah it looks like the Showcase works with CSP as does my production app because I configure my panels with `options="#{showcaseLayout.options}"` and not right in the panels...

**Comment by lih13800** [comment] 2024-04-04 16:57
Thank you.  We can use options attribute to workaround currently.

**Comment by melloware** [comment] 2024-04-04 17:17
Report back when you have it all working @lih13800 . Much appreciated!

**Comment by lih13800** [comment] 2024-04-05 16:14
Thanks, after I added  options attribute those errors are not exist any more. It works well now.

**Comment by melloware** [comment] 2024-04-05 16:22
Nice I will close this as "workaround provided" as I don't think I will ever be able to fix the core layout.js

**Closed as completed by melloware** 2024-04-05 16:22 UTC
Labels: defect, :trophy: workaround
