### ISSUE TITLE
Layout: Uncaught TypeError: v is undefined

### ISSUE THREAD

**Issue by StevenHachel** [primefaces-extensions/primefaces-extensions#693] opened 2022-01-18 09:15 UTC
**Environment:**
 - PF Version: 8.0.14
 - PrimeFaces Extensions 8.0.5
 - JSF version: 2.3.9
 - OmniFaces version: 2.7.14
 - JavaEE vesion: 8.0.1
 - WebLogic 14.1.1.0.0
 - Affected browsers: Chrome, Firefox
 
Since the switch to JavaEE8, JSF 2.3 and WebLogic 14, I have been getting this message for constellations that I cannot explain and the ajaxStatus also stops and does not set it to complete, so that the application cannot continue to be executed, except via a refresh of the page.

Is it somehow known how it happens that the variable "v" suddenly no longer exists?

Firefox console error message:
```
Uncaught TypeError: v is undefined
    bindEvents http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:188
    jQuery 4
    N     http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:76
    va    http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:139
    each jQuery
    va    http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:139
    nb    http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:87
layout.js.xhtml:188:4
    bindEvents http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:188
    jQuery 4
    N      http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:76
    va     http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:139
    each   jQuery
    va     http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:139
    nb     http://localhost:7001/merlin/javax.faces.resource/layout/layout.js.xhtml?ln=primefaces-extensions&v=8.0.5:87
```

Steven

**Comment by jepsar** [comment] 2022-01-18 10:57
Transferred the issue

**Comment by melloware** [comment] 2022-01-18 13:02
@StevenHachel  What version of PF 8.0.0 or an elite release?

**Comment by StevenHachel** [comment] 2022-01-18 13:40
@melloware PF 8.0.14 Elite. Sorry.
Updated first entry.

**Comment by melloware** [comment] 2022-01-18 13:42
OK let me see if I can reproduce.

**Comment by melloware** [comment] 2022-01-19 21:29
Attached is a reproducer run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

I can't reproduce.  I am using PF 8.0.5 with PF Elite 8.0.14.  

[pfe-693.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/7900689/pfe-693.zip)

**Comment by melloware** [comment] 2022-01-22 13:12
@StevenHachel is it safe to close this ticket have you gotten to the bottom of your issue?

**Comment by StevenHachel** [comment] 2022-01-22 13:56
@melloware 
Hello, I found something that may have an indirect connection, but is useful in my project.

It's about the <p:clientValidator event="keyup"/>. When using it, a JavaScript exception is always triggered.
```
Uncaught TypeError: PrimeFaces.vi is not a function
    onchange http://localhost:8080/primefaces-test/:1

```

Just type something in the field. Possibly that is also the trigger of the whole thing.

Profil: mojarra23
[pfe-693.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/7918463/pfe-693.zip)

**Comment by melloware** [comment] 2022-01-22 15:12
OK this is not Layout related its core PrimeFaces.  Please report the bug there.  I just tested and it's still a problem with 11.0.0 so this bug looks like it has been there for a while.

I am able to reproduce the same error with Layout removed entirely.  Just...

```xml
        <h:form>
                    <h1>CENTER</h1>
                    <div class="card">
                        <h:panelGrid columns="4" cellpadding="7">
                            <h:outputLabel for="text" value="Text: (Change)"/>
                            <p:inputText id="text" value="#{validationView.text}" required="true">
                                <f:validateLength minimum="2" maximum="5"/>
                                <p:clientValidator/>
                            </p:inputText>
                            <p:message for="text" display="icon"/>
                            <h:outputText value="#{validationView.text}"/>

                            <h:outputLabel for="integer" value="Integer: (Keyup)"/>
                            <p:inputText id="integer" value="#{validationView.integer}">
                                <p:clientValidator event="keyup"/>
                            </p:inputText>
                            <p:message for="integer" display="icon"/>
                            <h:outputText value="#{validationView.integer}"/>
                        </h:panelGrid>

                        <p:commandButton value="Save" ajax="false" icon="pi pi-check" validateClient="true"
                                         styleClass="p-mt-3"/>
                    </div>
        </h:form>
```

It looks like this is the problem..

```xml
<p:inputText id="integer" value="#{validationView.integer}">
                                <p:clientValidator event="keyup"/>
                            </p:inputText>
```

**Comment by melloware** [comment] 2022-01-23 16:28
I will leave open until you create the issue over at PF and then I will link this issue to it.

**Comment by StevenHachel** [comment] 2022-01-24 09:18
@melloware 
New issue is created. https://github.com/primefaces/primefaces/issues/8318

**Closed as completed** 2022-01-24 12:23 UTC
Labels: :no_entry: invalid
