### ISSUE TITLE
Showcase: RemoteCommand parameter examples do not work using JDK 11

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#166] opened 2020-10-04 09:40 UTC
Works in production, no longer when built from source:

Oct 04, 2020 11:34:47 AM org.primefaces.application.exceptionhandler.PrimeExceptionHandler logException
SEVERE: Unparseable date: "5/14/07 12:55:42 PM"
java.text.ParseException: Unparseable date: "5/14/07 12:55:42 PM"
	at java.base/java.text.DateFormat.parse(DateFormat.java:395)
	at javax.faces.convert.DateTimeConverter$FormatWrapper.parse(DateTimeConverter.java:489)
	at javax.faces.convert.DateTimeConverter$FormatWrapper.access$100(DateTimeConverter.java:470)
	at javax.faces.convert.DateTimeConverter.getAsObject(DateTimeConverter.java:437)
	at org.primefaces.extensions.component.remotecommand.RemoteCommandRenderer.decode(RemoteCommandRenderer.java:77)

**Comment by melloware** [comment] 2020-10-04 17:32
I will investigate.

**Comment by melloware** [comment] 2020-10-05 13:11
I wonder if it is `locale` related?  I am running it locally and its working fine for me?  My browser is English United States locale since I live in the US.

**Comment by jepsar** [comment] 2020-10-06 14:09
My browser is also set to US English as the default (I prefer it over Dutch online)... weird though that it works in production for me.

**Comment by melloware** [comment] 2020-10-06 14:28
So is it failing on localhost for you in the latest showcase?

**Comment by jepsar** [comment] 2020-10-06 14:44
Yes, I assumed it was caused something changed in the showcase recently.

**Comment by melloware** [comment] 2020-10-06 14:46
I wonder if its a JDK issue with `short` format?
```xml
<f:convertDateTime type="both" dateStyle="short" locale="en"/>
```

I am using JDK8.

**Comment by jepsar** [comment] 2020-10-06 14:48
Ah, I'm on 11 by default. Let me see if it works with 8.

**Comment by melloware** [comment] 2020-10-06 14:50
We have seen this before with JDK11: https://github.com/primefaces/primefaces/issues/5696

**Comment by jepsar** [comment] 2020-10-07 05:21
It's indeed an issue with JDK 11.

**Comment by GedMarc** [comment] 2020-10-07 07:23
guys no it is not an issue 
LocalDate and Instant have changed between JDK 8 and JDK 9 and up, you have to change your code (or use META-INF/versions), The precision for deserialization and serialization (0..9fractional nano) as well 

https://blog.joda.org/2017/02/java-time-jsr-310-enhancements-java-9.html

Further more - locale's are not really enabled anymore by default, especially in module mode, so keep an eye out for that :
![image](https://user-images.githubusercontent.com/5367513/95299895-b590cf80-087e-11eb-9d9c-3904d1ed7288.png)

this is by design

**Comment by jepsar** [comment] 2020-10-07 07:35
@GedMarc Yes, I meant that the issue in the showcase only occurs when the showcase is run with JDK 11. Thanks for pointing that out though. @melloware does this require any action? PF targets JDK 8, right?

**Comment by tandraschko** [comment] 2020-10-07 07:49
PF targets all versions IMO but LTS for sure (8, 11, 15/16?)

**Comment by GedMarc** [comment] 2020-10-07 10:04
8 / 11 /17 ?

I'm running PF on JDK 14 JLink build here (Mojarra 'ish) https://pfshowcase.guicedee.com/
I'll see if i can replicate and resolve, it will definitely need a multi-version jar though, you guys ok with that?

**Comment by GedMarc** [comment] 2020-10-07 10:09
mmm, please assist in replication - can't seem to or i've fixed in somewhere on my side already (will make the pr easier..)

**Comment by melloware** [comment] 2020-10-07 11:45
You can read the whole thread or check out @christophs78 debugging the problem: https://github.com/primefaces/primefaces/issues/5696#issuecomment-605646729

and since this conversion is happening inside `f:convertDateTime` its counting on the JDK to be correct.

Especially if you use Locale `en_GB` in OpenJDK 11 you will see the issue.

**Comment by melloware** [comment] 2020-10-10 19:39
For now I just fixed the examples to work in JDK8 or 11+

**Closed as completed** 2020-10-10 19:38 UTC
Labels: defect
