### ISSUE TITLE
CommandButtonSingleClick: Respect actionListener as well as action

### ISSUE THREAD

**Issue by Exandra** [primefaces-extensions/primefaces-extensions#227] opened 2020-11-09 16:31 UTC
**Describe the bug**
The CommandButtonSingleClick renderer appends new JavaScript code to the existing JavaScript code on each update. This increases the size of the DOM tree, and subsequently the data transmitted over the network, continually.

This behavior results, on complex pages, after a short while in multiple megabyte data per update/click.

**Environment:**
 - PF Version: 8.0.3
 - JSF + version: Mojarra 2.3
 - Affected browsers: Chrome, Firefox

**To Reproduce**
1. git clone https://github.com/Exandra/primefaces-test
2. cd primefaces-test
3. mvn clean jetty:run -Pmojarra23
4. Open http://localhost:8080/primefaces-test/
5. Open your web inspector
6. Click repeately on the button labeled "Update @form" and keep an eye on the transmitted data or check the size of the DOM
(also works by switching pages or similar updates)

**Expected behavior**
The size of DOM/transmitted data should be nearly constant even after ten updates.
Remove the CommandButtonSingleClickRenderer from your faces-config.xml to compare your results with vanilla primefaces.

**JavaScript**
With each update, the CommandButton onclick gets longer and longer with more disable/enable statements:
`var w = PF('widget_frmTest_j_idt6_1_j_idt8');
if (w) {
	w.disable();
};`

**Comment by jepsar** [comment] 2020-11-09 19:50
This is a duplicate of https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/761

Please upgrade to PFE 8.0.4

**Comment by melloware** [comment] 2020-11-09 20:49
Yes please use 8.0.4 like this and report back.
```xml
<dependency>
    <groupId>org.primefaces.extensions</groupId>
    <artifactId>primefaces-extensions</artifactId>
    <version>8.0.4</version>
</dependency>
```

**Comment by jepsar** [comment] 2020-11-09 20:57
I tested the provided project with 8.0.4 and it solved the issue

**Comment by Exandra** [comment] 2020-11-11 09:00
Sorry for the late reply. How embarrassing that I never noticed that there are sub-releases of primefaces-extensions 🤭. 

Unfortunately, I cannot get my provided test case to run correctly. As soon as I switch to primefaces-extensions 8.0.1 or above, the buttons are no longer disabled when I click them. I have tried different combinations like Primefaces 8.0.5/Extensions 8.0.4 or Primefaces 8.0.4/Extensions 8.0.4 etc. 

I extended my provided project by adding a 2s Thread.sleep delay button. Do I have to modify my renderer in faces-config.xml to get it to work? I checked the extensions showcase, but I don't understand why it works there but not for me. 😥

**Comment by melloware** [comment] 2020-11-11 12:53
In your faces-config.xml you need to add:
```xml
<render-kit>
<renderer>
    <component-family>org.primefaces.component</component-family>
    <renderer-type>org.primefaces.component.CommandButtonRenderer</renderer-type>
    <renderer-class>org.primefaces.extensions.renderer.CommandButtonSingleClickRenderer</renderer-class>
</renderer>
</render-kit>
```

To enable this renderer.

**Comment by Exandra** [comment] 2020-11-11 14:18
I already added the renderer to my faces-config.xml ( https://github.com/Exandra/primefaces-test/blob/master/src/main/webapp/WEB-INF/faces-config.xml ) 
Functionally whise, it works with primefaces-extensions 8.0: (aside from the bug in this ticket)

```
	<dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>8.0</version>
        </dependency>
```

If I change my pom.xml ( https://github.com/Exandra/primefaces-test/blob/master/pom.xml ) to 
```
	<dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>8.0.4</version>
        </dependency>
```
The renderer don't work anymore. I can click the button multiple times. Are there any more changes required to migrate from 8.0 to 8.0.4?

**Comment by melloware** [comment] 2020-11-11 14:20
Can you provide a test case like above proving its not working?

**Comment by Exandra** [comment] 2020-11-11 14:34
I updated my primefaces-test fork.

primefaces-extensions 8.0.4:
1. git clone https://github.com/Exandra/primefaces-test
2. cd primefaces-test
3. mvn clean jetty:run -Pmojarra23
4. Open http://localhost:8080/primefaces-test/
The button at the top won't disable on click. (tested in firefox, chrome, chrome edge and IE11)

Quit jetty and set primefaces-extensions version in poml.xml to 8.0. Repeat above procedure. The button at the top will be disabled on click an re-enabled after 2 seconds automatically.

I'm using Primefaces 8.0.4/8.0.5 from Elite and Primefaces Extensions from Maven Central:
> SHA1:
> 9223a1a550195bd1cce0d8e610b43de325e6b98c *primefaces-8.0.4.jar
> c75eac9cf054256a892e915e90caf153fa91d9f8 *primefaces-8.0.5.jar
> 6f53d359d3a84d35634746e0510fd379aca7c8d7 *primefaces-extensions-8.0.jar
> 953adbf2f996bc5b40baa3e927ecf87c419d1e90 *primefaces-extensions-8.0.4.jar

**Comment by melloware** [comment] 2020-11-11 14:37
Reopened and assigned to @jepsar to investigate.

**Comment by melloware** [comment] 2020-11-11 14:41
Also what happens when you are on PF Community 8.0 and PFE 8.0.4?  We typically only test here with 8.0 Community release.  Just curious.

**Comment by melloware** [comment] 2020-11-11 15:12
OK I think I see the bug.  It works if you use `action` but not `actionListener`.

Current code:
```java
protected boolean isEligible(final CommandButton button) {
        return button.isAjax()
                    && button.isRendered()
                    && button.getActionExpression() != null
                    && !button.isDisabled()
                    && !isConfirmation(button);
    }
```

I think needs to be...
```java
    protected boolean isEligible(final CommandButton button) {
        final ActionListener[] listeners = button.getActionListeners();
        return button.isAjax()
                    && button.isRendered()
                    && (button.getActionExpression() != null || (listeners != null && listeners.length > 0))
                    && !button.isDisabled()
                    && !isConfirmation(button);
    }
```

**Comment by melloware** [comment] 2020-11-11 15:21
I just submitted a fix for this for 9.0. if you need this right now in your own project using 8.0 jut copy the entire CommandSingleClickRenderer into your project and just change the faces-config.xml class name to point to your local renderer.

**Closed as completed** 2020-11-11 15:20 UTC
Labels: defect

**Comment by Exandra** [comment] 2020-11-11 16:57
Thank you. I just copied the new renderer in our project and so far it looks very good. 😊

**Comment by melloware** [comment] 2020-11-11 17:33
Excellent. Thanks for reporting and testing this issue.
