### ISSUE TITLE
LetterAvatar: not rendered correctly using small height values

### ISSUE THREAD

**Issue by marcelocaser** [primefaces-extensions/primefaces-extensions#160] opened 2020-09-29 14:06 UTC
**Describe the bug**
After update to 8.0 to 8.0.4 the component Letter Avatar doesn't rendered correct! See above:

**Reproducer**
Use: `<pe:letterAvatar value="#{twebusuariosTO.nomeCompleto}" size="1rem" rounded="false"/>`

![Opera Instantâneo_2020-09-29_100613_localhost](https://user-images.githubusercontent.com/4403920/94570066-cd47d280-0244-11eb-81b1-8ffa441fb832.png)

**Environment:**
 - PF Version: 8.0
 - JSF + version: Mojarra 2.3.14
 - Affected browsers: ALL

**To Reproduce**
- Just use `<pe:letterAvater/>` in some page!

**Expected behavior**
![Opera Instantâneo_2020-09-29_100433_10 5 103 241](https://user-images.githubusercontent.com/4403920/94569973-b3a68b00-0244-11eb-8680-02ea4b164508.png)

**Sample XHTML**
-Not necessary!

**Sample Bean**
-Not necessary!

**Comment by melloware** [comment] 2020-09-29 14:08
can you paste your before and after screenshots too please

**Comment by marcelocaser** [comment] 2020-09-29 14:14
added images

**Comment by jepsar** [comment] 2020-09-29 14:16
@melloware do you want me to have a look?

**Comment by melloware** [comment] 2020-09-29 14:31
yep looks like a regression of this issue: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/695

attached test case: https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/3141695/pfe-la.zip

**Comment by melloware** [comment] 2020-09-29 14:31
assigned to you @jepsar

**Comment by jepsar** [comment] 2020-09-29 14:59
I cannot fully reproduce this. I added this to the showcase:
```xhtml
<p:dataTable value="#{['Optimus Prime','PrimeFaces Extensions']}" var="name">
    <p:column headerText="Name">
        <pe:letterAvatar value="#{name}" size="1rem" rounded="false"/>
        #{name}
    </p:column>
</p:dataTable>
```
which renders as

<img width="351" alt="Screen Shot 2020-09-29 at 16 56 50" src="https://user-images.githubusercontent.com/7500178/94575700-cdf85d00-0274-11eb-9cfc-48100937b620.png">

The line height is not perfect, but that's all (it seems). (Chrome Version 85.0.4183.121 (Official Build) (64-bit) on MacOS).

**Comment by melloware** [comment] 2020-09-29 15:02
what happens when you update="datatable" same as sorting or paging or filtering

**Comment by jepsar** [comment] 2020-09-29 15:06
<img width="369" alt="Screen Shot 2020-09-29 at 17 05 56" src="https://user-images.githubusercontent.com/7500178/94576828-15cbb400-0276-11eb-83bd-9df88ce4c6cf.png">

Looks the same..

**Comment by melloware** [comment] 2020-09-29 15:12
Agreed I can't reproduce...
[pfe-la.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/5300054/pfe-la.zip)

However I do notice the color spread is not that great?

![image](https://user-images.githubusercontent.com/4399574/94577500-ab4e5000-0244-11eb-9e64-6a5d9bd38de4.png)

**Comment by jepsar** [comment] 2020-09-29 15:22
> However I do notice the color spread is not that great?

Caused by:
```java
    public static int hue(final String str) {
        return Math.abs(hash(str) % 360);
    }
```

This is giving you all the possible hue values. A better spread would be something like:

```java
    public static int hue(final String str) {
        return Math.abs((hash(str) % 60) * 6);
    }
```

which gives 60 possibilities instead of all 360.

**Comment by melloware** [comment] 2020-09-29 15:24
maybe do 60 if string length == 1 and 360 for all others?

**Comment by melloware** [comment] 2020-09-29 15:25
oh i actually like your solution better.  i see the * 6 now

**Comment by jepsar** [comment] 2020-09-29 15:25
Also, I think we can simply use `string.hashCode()` instead of calculating a hash.

**Comment by jepsar** [comment] 2020-09-29 15:28
I'll do some tweaks, but that won't fix the reported issue. I don't think there were changes between 8.0.4 and 9.0.

**Comment by melloware** [comment] 2020-09-29 15:28
up to you!  yeah i think this is a non issue.

**Comment by marcelocaser** [comment] 2020-09-29 15:33
Look: with sample (pfe-la.zip)

`<pe:letterAvatar value="#{car.brand}" height="24" width="24" rounded="false"/>`
![Opera Instantâneo_2020-09-29_123057_localhost](https://user-images.githubusercontent.com/4403920/94580106-e73ae280-024f-11eb-993b-eecefb8fbbf2.png)

`<pe:letterAvatar value="#{car.brand}" size="1rem" rounded="false"/>`
![Opera Instantâneo_2020-09-29_123203_localhost](https://user-images.githubusercontent.com/4403920/94580085-e1450180-024f-11eb-8a8e-91f6ad137aa8.png)

**Comment by jepsar** [comment] 2020-09-29 15:36
@marcelocaser can you please inspect the inner span with class `ui-letteravatar-initials` and disable the `top` property. Does that solve the issue for you?

**Comment by jepsar** [comment] 2020-09-29 15:37
<img width="752" alt="Screen Shot 2020-09-29 at 17 37 13" src="https://user-images.githubusercontent.com/7500178/94580648-72c96900-027a-11eb-8f25-78c2b332396b.png">

**Closed as completed** 2020-09-29 16:19 UTC
Labels: defect
